### ISSUE TITLE
Error handling response: TypeError: Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by KoalaBear84** [andryou/Decreased-Productivity#11]
Every page I get this, I don't know why. Maybe it is some incompatibility with Ghostery or Adblock Plus.

```
search:1 Error handling response: TypeError: Cannot read property 'enable' of undefined
    at chrome-extension://nlbpiflhmdcklcbihngeffpmoklbiooj/js/dp.js:238:15
jquery.js:2 jQuery.Deferred exception: Cannot read property 'enableToggle' of undefined TypeError: Cannot read property 'enableToggle' of undefined
    at HTMLDocument.<anonymous> (chrome-extension://nlbpiflhmdcklcbihngeffpmoklbiooj/js/dp.js:236:22)
    at j (chrome-extension://nlbpiflhmdcklcbihngeffpmoklbiooj/js/jquery.js:2:29588)
    at k (chrome-extension://nlbpiflhmdcklcbihngeffpmoklbiooj/js/jquery.js:2:29902) undefined
```

Screenshot:
![image](https://user-images.githubusercontent.com/5886900/55713078-3b189280-59f0-11e9-9d2a-4df90d9b88a9.png)

**Comment by KoalaBear84** [comment]
Any news?
